version: '3.8'

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: db
    image: roiers/home-library:db
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command:
      ['postgres', '-c', 'logging_collector=on', '-c', 'log_statement=all']
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    networks:
      - my-home-library

  my-home-library-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-home-library-app
    image: roiers/home-library:app
    restart: always
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DB_DOCKER_URL}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - my-home-library

networks:
  my-home-library:
    driver: bridge

volumes:
  postgres-data:
  postgres-logs:
